### ISSUE TITLE
chapter1-1的博客和demo对不上

### ISSUE THREAD

**Issue by FireJohnny** [dyc87112/SpringBoot-Learning#71]
![image](https://user-images.githubusercontent.com/19511703/130399953-4b61c3ef-a77f-47f9-bc3c-35d8891260e4.png)
这个是你定义的格式controller的package但是demo里面不是 还是在chapter11之下，这个在我本地测试中是错误的

**Comment by dyc87112** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    这个不强制要求的。
        
            
        
    
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                didi
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2021年08月23日 ***@***.***> 写道： 






这个是你定义的格式controller的package但是demo里面不是 还是在chapter11之下，这个在我本地测试中是错误的



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dyc87112** [comment]
![image](https://user-images.githubusercontent.com/3391170/130565816-39a5d854-c976-497a-9f31-de4ca59b133d.png)

这个不强制要求的。
